name: tanysu
description: Dating app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.0.0
  shared_preferences: ^2.1.2
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.3
  flutter_phoenix: ^1.1.1
  google_fonts: ^5.1.0
  path_provider: ^2.0.6
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: '#4A2160'
  image: "assets/images/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: any
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/
