name: tanysu
description: Dating app.
publish_to: 'none'
version: 5.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  flutter_phoenix: ^1.1.1
  google_fonts: ^5.1.0
  path_provider: ^2.0.6
  mask_text_input_formatter: ^2.5.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  dotted_border: ^2.0.0+3
  connectivity_plus: ^4.0.2
  flutter_datetime_picker_plus: ^2.1.0
  provider: ^6.0.5
  get: ^4.6.6
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  appinio_swiper: ^2.1.0
  socket_io_client: ^2.0.3+1
  webview_flutter_plus: ^0.3.0+2
  shimmer: ^3.0.0
  grouped_list: ^5.1.2 
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  awesome_notifications: ^0.8.2
  firebase_messaging: ^14.7.5
  font_awesome_flutter: ^9.2.0

  
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  web_socket_channel: ^2.4.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  zego_uikit_prebuilt_live_streaming: ^3.5.4

flutter_native_splash:
  android: true
  ios: true

  image: "assets/icons/splash_icon.png"
  background_image: assets/background/background_splash.png
  background_image_dark: assets/background/background_splash.png


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: any
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/gifts/
    - assets/background/
    - assets/icons/
    - assets/icons/enter_method/
    - assets/icons/report_icons/
    - assets/icons/stream/
    - assets/icons/navigation_icons/
    - assets/privacy.html
    - assets/privacy_ru.html
    - assets/privacy_kk.html
    - assets/terms.html
    - assets/terms_ru.html
    - assets/terms_kk.html
