const List<String> gifts = [
  'assets/gifts/1.svg',
  'assets/gifts/2.svg',
  'assets/gifts/3.svg',
  'assets/gifts/4.svg',
  'assets/gifts/5.svg',
  'assets/gifts/6.svg',
  'assets/gifts/7.svg',
  'assets/gifts/8.svg',
  // 'assets/gifts/9.svg',
  'assets/gifts/10.svg',
  'assets/gifts/11.svg',
  'assets/gifts/12.svg',
  'assets/gifts/13.svg',
  'assets/gifts/14.svg',
  'assets/gifts/15.svg',
  'assets/gifts/16.svg',
  'assets/gifts/17.svg',
  'assets/gifts/18.svg',
  'assets/gifts/19.svg',
  'assets/gifts/20.svg',
];
